const ActionType = {
  FETCH_CHORES_START: 'FETCH_CHORES_START',
  FETCH_CHORES_SUCCESS: 'FETCH_CHORES_SUCCESS',
  FETCH_CHORES_FAILURE: 'FETCH_CHORES_FAILURE',
  CREATE_CHORE: 'CREATE_CHORE'
}

export default ActionType
